api = "0.6"

[buildpack]
  homepage = "https://github.com/paketo-community/staticfile"
  id = "paketo-community/staticfile"
  name = "Staticfile Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml", "server_configs/nginx.conf"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
