api = "0.2"

[buildpack]
  id = "paketo-community/staticfile"
  name = "Staticfile Buildpack"
  version = "0.0.2"

[metadata]
  include-files = ["bin/build","bin/detect","bin/run","buildpack.toml","server_configs/nginx.conf"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

